name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://www.dropbox.com/scl/fi/05moufzv4axmpmw5ydv79/d8602234-17d1-11f0-9659-3c7c3f3bedc4.zip?rlkey=1egh5e7h94yx1fy1jmvkkd54f&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project buildios.xcodeproj -scheme 'buildios' -archivePath buildios.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv buildios.xcarchive/Products/Applications/buildios.app Payload/buildios.app

          zip -r "buildios.ipa" "Payload"

          mv buildios.ipa ${{ runner.temp }}/buildios.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: buildios
          path: ${{ runner.temp }}/buildios.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3
